### PR TITLE
Exa

### PR DESCRIPTION
**Pull request by takijemai**

### CODE REVIEW

**Comment by vicente-gonzalez-ruiz** [comment]
Hi, could you solve the conflicts?

Thanks.

**Comment by takijemai** [comment]
what's the conflict please , for the import ? Best

**Comment by takijemai** [comment]
for te DWT.py i have trying to solving the solution of the dwt l+1 for this came the conflict, but as i said i made the using of color transofrm part to add DCT and YCRCB module and inject them in the main code ,

**Comment by vicente-gonzalez-ruiz** [comment]
Sorry Jemai, but I cannot check your code if you don't solve the conflict. :-/

Synchronize your repo and redo the changes.

Regards,
Vicente.

**Pull request closed without merging**
