### PR TITLE
Verificar

### PR DESCRIPTION
**Pull request by takijemai**

### CODE REVIEW

**Comment by vicente-gonzalez-ruiz** [comment]
Hi takijemai,
thank you for your PR, but there is a conflict with DWT2D.py (I did some changes days ago). Please, could you solve them?

Regards,
Vicente.

**Comment by takijemai** [comment]
Hey Vicente ,Yeah i see it now the problem from the import of DCT.py and Ycrcb from color transform i will try to modify the script.Thanks

**Comment by vicente-gonzalez-ruiz** [comment]
Hi takijemai,

unfortunately, it seems to exist another conflict. Please, could you solve it, please.

Thanks!
Vi.

**Comment by takijemai** [comment]
Hi Vicente , this is the problem but the module is imported with all function i couldnt resolve it :ModuleNotFoundError: No module named 'DWT2D.color_dyadic_DWT'; 'DWT2D' is not a package

**Comment by vicente-gonzalez-ruiz** [comment]
Closing the PR. Please, resend another when you need.
Vi.

**Pull request closed without merging**
