### PR TITLE
re

### PR DESCRIPTION
**Pull request by takijemai**
hi sir, i have make the PR after the changes i dont know why there is the conflict

### CODE REVIEW

**Comment by takijemai** [comment]
i couldnt resolve the issue of te code i dont know why every thing is working in my side its so strange!!!!

**Comment by vicente-gonzalez-ruiz** [comment]
A conflict only means that your code cannot be merged automatically with the main branch. What do you see when you are going to do the PR? Take a screenshot in that moment and send it to me.

Anyway, have you tried to click in the "Resolve conflicts" button that appears below?

**Comment by takijemai** [comment]
Yes i know this is the screenshot 
image

**Comment by takijemai** [comment]
yeah its working well , i fixed it

**Pull request closed without merging**
